name: Simple HTML Check

on:
  push:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tidy
        run: sudo apt-get update && sudo apt-get install -y tidy

      - name: Check HTML
        run: tidy -qe index.html
