name: Simple HTML Check

on:
  push:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tidy
        run: sudo apt-get update && sudo apt-get install -y tidy

      - name: Check HTML
        run: tidy -qe index.html
        
      - name: Test HTML content
        run: grep -q "Hello" index.html

      - name: Build no need for html
        run: echo "Build on Html"

      - name: Deploy to server
        run: echo "Deploy Complete"
        # scp -r ./dist user@server:/var/www/html

      - name: Check homepage after deploy
        run: echo "Perfect everything"
          #curl -I https://yourserver.com | grep "200 OK"
